import { addEquipmentToProfiles, getProfiles, Profile } from '../../helpers'

export const adeptusAstartesEquipment = {
  STORM_SHIELD: {
    label: 'Storm shield',
  },
}

export const deathwatchVeteranWarrior: Profile = {
  name: 'DEATHWATCH VETERAN (WARRIOR)',
  movement: 6,
  apl: 3,
  groupActivation: 1,
  defense: 3,
  save: 3,
  saveCritical: 6,
  wounds: 11,
  ballisticSkill: 3,
  weaponSkill: 3,
  weapons: [
    ...getProfiles('Deathwatch Boltgun'),
    ...getProfiles('Deathwatch Shotgun'),
    ...getProfiles('Stalker pattern boltgun'),
    ...getProfiles('Storm bolter'),
    ...getProfiles('Fists'),
    ...getProfiles('Power weapon'),
  ],
}
export const deathwatchVeteranFighter: Profile = {
  name: 'DEATHWATCH VETERAN (FIGHTER)',
  movement: 6,
  apl: 3,
  groupActivation: 1,
  defense: 3,
  save: 3,
  saveCritical: 6,
  wounds: 11,
  ballisticSkill: 3,
  weaponSkill: 3,
  weapons: [
    ...getProfiles('Bolt pistol'),
    ...getProfiles('Grav-pistol'),
    ...getProfiles('Hand flamer'),
    ...getProfiles('Inferno pistol'),
    ...getProfiles('Plasma pistol'),
    ...getProfiles('Chainsword'),
    ...getProfiles('Heavy thunder hammer'),
    ...getProfiles('Lightning claw'),
    ...getProfiles('Lightning claws'),
    ...getProfiles('Power fist'),
    ...getProfiles('Power maul'),
    ...getProfiles('Power weapon'),
    ...getProfiles('Thunder hammer'),
  ],
}
export const deathwatchVeteranGunner: Profile = {
  name: 'DEATHWATCH VETERAN (GUNNER)',
  movement: 6,
  apl: 3,
  groupActivation: 1,
  defense: 3,
  save: 3,
  saveCritical: 6,
  wounds: 11,
  ballisticSkill: 3,
  weaponSkill: 3,
  weapons: [
    ...getProfiles('Combi-flamer'),
    ...getProfiles('Combi-grav'),
    ...getProfiles('Combi-melta'),
    ...getProfiles('Combi-plasma'),
    ...getProfiles('Deathwatch Boltgun'),
    ...getProfiles('Flamer'),
    ...getProfiles('Grav-gun'),
    ...getProfiles('Meltagun'),
    ...getProfiles('Plasma gun'),
    ...getProfiles('Fists'),
  ],
}
export const deathwatchVeteranHeavyGunner: Profile = {
  name: 'DEATHWATCH VETERAN (HEAVY GUNNER)',
  movement: 6,
  apl: 3,
  groupActivation: 1,
  defense: 3,
  save: 3,
  saveCritical: 6,
  wounds: 11,
  ballisticSkill: 3,
  weaponSkill: 3,
  weapons: [
    ...getProfiles('Frag Cannon'),
    ...getProfiles('Infernus Heavy Bolter'),
    ...getProfiles('Missile Launcher'),
    ...getProfiles('Fists'),
  ],
}
export const deathwatchVeteranWatchSergeant: Profile = {
  name: 'DEATHWATCH VETERAN WATCH SERGEANT',
  movement: 6,
  apl: 3,
  groupActivation: 1,
  defense: 3,
  save: 3,
  saveCritical: 6,
  wounds: 12,
  ballisticSkill: 2,
  weaponSkill: 2,
  weapons: [
    ...getProfiles('Deathwatch Boltgun'),
    ...getProfiles('Deathwatch Shotgun'),
    ...getProfiles('Combi-flamer'),
    ...getProfiles('Combi-grav'),
    ...getProfiles('Combi-melta'),
    ...getProfiles('Combi-plasma'),
    ...getProfiles('Flamer'),
    ...getProfiles('Grav-gun'),
    ...getProfiles('Meltagun'),
    ...getProfiles('Plasma gun'),
    ...getProfiles('Stalker pattern boltgun'),
    ...getProfiles('Storm bolter'),
    ...getProfiles('Bolt pistol'),
    ...getProfiles('Grav-pistol'),
    ...getProfiles('Hand flamer'),
    ...getProfiles('Inferno pistol'),
    ...getProfiles('Plasma pistol'),
    ...getProfiles('Fists'),
    ...getProfiles('Heavy thunder hammer'),
    ...getProfiles('Lightning claws'),
    ...getProfiles('Chainsword'),
    ...getProfiles('Lightning claw'),
    ...getProfiles('Power fist'),
    ...getProfiles('Power maul'),
    ...getProfiles('Power weapon'),
    ...getProfiles('Thunder hammer'),
    ...addEquipmentToProfiles(getProfiles('Xenophase blade'), [adeptusAstartesEquipment.STORM_SHIELD]),
  ],
}

export const adeptusAstartesStats = {
  name: 'Adeptus Astartes',
  fireTeams: [
    {
      name: 'Deathwatch Veterans',
      dataSheets: [
        deathwatchVeteranWarrior,
        deathwatchVeteranFighter,
        deathwatchVeteranGunner,
        deathwatchVeteranHeavyGunner,
        deathwatchVeteranWatchSergeant,
      ],
    },
  ],
}
