import { specialRules, criticalRules, Rule } from '../rules'

export interface Weapon {
  name: string
  profile: string
  attackDice: number
  weaponSkillAdjustment?: number
  damage: number
  damageCritical: number
  specialRules: Rule[]
  criticalRules: Rule[]
  type: 'RANGED' | 'MELEE'
}

export const weapons: Weapon[] = [
  {
    name: 'Heavy thunder hammer',
    profile: '',
    attackDice: 5,
    weaponSkillAdjustment: 1,
    damage: 6,
    damageCritical: 8,
    specialRules: [],
    criticalRules: [criticalRules.STUN],
    type: 'MELEE',
  },
  {
    name: 'Power fist',
    profile: '',
    attackDice: 5,
    weaponSkillAdjustment: 1,
    damage: 5,
    damageCritical: 7,
    specialRules: [specialRules.BRUTAL],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Power weapon',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 6,
    specialRules: [specialRules.LETHAL5],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Deathwatch Boltgun',
    profile: 'Dragonfire',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.NO_COVER],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Boltgun',
    profile: 'Hellfire',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [criticalRules.RENDING],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Boltgun',
    profile: 'Kraken',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Boltgun',
    profile: 'Vengeance',
    attackDice: 4,
    damage: 4,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Shotgun',
    profile: 'Cryptclearer',
    attackDice: 4,
    damage: 4,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Shotgun',
    profile: 'Wyrmsbreath',
    attackDice: 5,
    weaponSkillAdjustment: -1,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.RNG3, specialRules.TORRENT],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Shotgun',
    profile: 'Xenopurge',
    attackDice: 4,
    weaponSkillAdjustment: -1,
    damage: 3,
    damageCritical: 5,
    specialRules: [specialRules.RNG6],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Stalker pattern boltgun',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.HEAVY, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Storm bolter',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RELENTLESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Frag Cannon',
    profile: 'Frag',
    attackDice: 4,
    damage: 4,
    damageCritical: 6,
    specialRules: [specialRules.BLAST2],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Frag Cannon',
    profile: 'Shell',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Auto bolt rifle',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.CEASELESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Heavy Bolter',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Heavy Bolter (CSM)',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Heavy Bolter (CSM)',
    profile: 'Malefic Rounds',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Heavy Bolter (CSM)',
    profile: 'Belt Feed',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE, specialRules.CEASELESS],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Infernus Heavy Bolter',
    profile: 'Heavy Bolter',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Infernus Heavy Bolter',
    profile: 'Heavy Flamer',
    attackDice: 6,
    weaponSkillAdjustment: -1,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.HEAVY, specialRules.RNG6, specialRules.TORRENT],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Missile Launcher',
    profile: 'Frag',
    attackDice: 4,
    damage: 3,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.BLAST2],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Missile Launcher',
    profile: 'Krak',
    attackDice: 4,
    damage: 5,
    damageCritical: 7,
    specialRules: [specialRules.HEAVY, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Boltgun (CSM)',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Boltgun (CSM)',
    profile: 'Belt Feed',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.CEASELESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Boltgun (CSM)',
    profile: 'Malefic Rounds',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Bolt pistol (CSM)',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RNG6],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Bolt pistol (CSM)',
    profile: 'Belt Feed',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RNG6, specialRules.CEASELESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Bolt pistol (CSM)',
    profile: 'Malefic Rounds',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RNG6],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Flamer',
    profile: '',
    attackDice: 5,
    weaponSkillAdjustment: -1,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.RNG6, specialRules.TORRENT],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Grav-gun',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.AP1, specialRules.GRAV],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Meltagun',
    profile: '',
    attackDice: 4,
    damage: 6,
    damageCritical: 3,
    specialRules: [specialRules.RNG6, specialRules.AP2],
    criticalRules: [criticalRules.MW4],
    type: 'RANGED',
  },
  {
    name: 'Plasma gun',
    profile: 'Standard',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Plasma gun',
    profile: 'Supercharge',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.AP2],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Combi-flamer',
    profile: '',
    attackDice: 5,
    weaponSkillAdjustment: -1,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.COMBI, specialRules.RNG6, specialRules.TORRENT, specialRules.LIMITED],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Combi-grav',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.COMBI, specialRules.AP1, specialRules.GRAV, specialRules.LIMITED],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Combi-melta',
    profile: '',
    attackDice: 4,
    damage: 6,
    damageCritical: 3,
    specialRules: [specialRules.COMBI, specialRules.RNG6, specialRules.AP2, specialRules.LIMITED],
    criticalRules: [criticalRules.MW4],
    type: 'RANGED',
  },
  {
    name: 'Combi-plasma',
    profile: 'Standard',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.COMBI, specialRules.AP1, specialRules.LIMITED],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Combi-plasma',
    profile: 'Supercharge',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.COMBI, specialRules.AP2, specialRules.LIMITED],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Bolt pistol',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RNG6],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Grav-pistol',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.RNG6, specialRules.AP1, specialRules.GRAV],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Hand flamer',
    profile: '',
    attackDice: 4,
    weaponSkillAdjustment: -1,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.RNG6, specialRules.TORRENT],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Inferno pistol',
    profile: '',
    attackDice: 4,
    damage: 5,
    damageCritical: 3,
    specialRules: [specialRules.RNG3, specialRules.AP2],
    criticalRules: [criticalRules.MW3],
    type: 'RANGED',
  },
  {
    name: 'Plasma pistol',
    profile: 'Standard',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.RNG6, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Plasma pistol',
    profile: 'Supercharge',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.RNG6, specialRules.AP2],
    criticalRules: [],
    type: 'RANGED',
  },
]
