import { Rule } from '../rules'
import { nonHeavyRangedWeapons } from './weapons/nonHeavyRangedWeapons'
import { heavyRangedWeapons } from './weapons/heavyRangedWeapons'
import { meleeWeapons } from './weapons/meleeWeapons'
import { pistols } from './weapons/pistols'

export type WeaponName =
  | 'Storm shield'
  | 'Xenophase blade'
  | 'Combat knife'
  | 'Fists'
  | 'Gun butt'
  | 'Arc maul'
  | 'Taser goad'
  | 'Chainsword'
  | 'Heavy thunder hammer'
  | 'Lightning claw'
  | 'Lightning claws'
  | 'Power fist'
  | 'Power maul'
  | 'Power pick'
  | 'Power weapon'
  | 'Thunder hammer'
  | 'Chordclaw and transonic razor'
  | 'Transonic blades'
  | 'Cult knife and claw'
  | 'Cult bonesword and claw'
  | 'Heavy rock cutter'
  | 'Heavy rock drill'
  | 'Heavy rock saw'
  | 'Cult bonesword and metamorph mutations'
  | 'Metamorph mutations'
  | 'Executioner greatblade'
  | 'Brutal assault weapon'
  | 'Autogun'
  | 'Shotgun'
  | 'Deathwatch boltgun'
  | 'Deathwatch shotgun'
  | 'Storm bolter'
  | 'Bolt carbine'
  | 'Frag cannon'
  | 'Auto bolt rifle'
  | 'Bolt rifle'
  | 'Stalker bolt rifle'
  | 'Boltgun'
  | 'Grenade launcher'
  | 'Webber'
  | 'Flamer'
  | 'Grav-gun'
  | 'Meltagun'
  | 'Plasma gun'
  | 'Combi-flamer'
  | 'Combi-grav'
  | 'Combi-melta'
  | 'Combi-plasma'
  | 'Hand flamer'
  | 'Plasma caliver'
  | 'Arc rifle'
  | 'Radium carbine'
  | 'Flechette blaster'
  | 'Stubcarbine'
  | 'Lash whip'
  | 'Guardian spear'
  | 'Sentinel blade'
  | 'Stalker pattern boltgun'
  | 'Heavy bolter'
  | 'Infernus heavy bolter'
  | 'Missile launcher'
  | 'Heavy stubber'
  | 'Mining laser'
  | 'Seismic cannon'
  | 'Galvanic rifle'
  | 'Transuranic arquebus'
  | 'Bolt pistol'
  | 'Special issue bolt pistol'
  | 'Grav-pistol'
  | 'Inferno pistol'
  | 'Plasma pistol'
  | 'Arc pistol'
  | 'Phosphor blast pistol'
  | 'Radium pistol'
  | 'Autopistol'
  | 'Web pistol'

export interface Weapon {
  name: WeaponName
  profile: string
  attackDice: number
  weaponBallisticSkillAdjustment?: number
  fixedWeaponBallisticSkill?: number
  damage: number
  damageCritical: number
  specialRules: Rule[]
  criticalRules: Rule[]
  equipment: Rule[]
  type: 'RANGED' | 'MELEE'
}

export const weapons: Weapon[] = [...meleeWeapons, ...nonHeavyRangedWeapons, ...heavyRangedWeapons, ...pistols]
