import { specialRules, criticalRules, Rule } from '../rules'

export interface Weapon {
  name: string
  profile: string
  attackDice: number
  weaponBallisticSkillAdjustment?: number
  fixedWeaponBallisticSkill?: number
  damage: number
  damageCritical: number
  specialRules: Rule[]
  criticalRules: Rule[]
  type: 'RANGED' | 'MELEE'
}

export const weapons: Weapon[] = [
  {
    name: 'Xenophase blade',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 6,
    specialRules: [specialRules.BRUTAL, specialRules.LETHAL5],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Fists',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Gun butt',
    profile: '',
    attackDice: 3,
    damage: 2,
    damageCritical: 3,
    specialRules: [],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Arc maul',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [],
    criticalRules: [criticalRules.STUN],
    type: 'MELEE',
  },
  {
    name: 'Taser goad',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.LETHAL5],
    criticalRules: [criticalRules.STUN],
    type: 'MELEE',
  },
  {
    name: 'Chainsword',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Heavy thunder hammer',
    profile: '',
    attackDice: 5,
    weaponBallisticSkillAdjustment: 1,
    damage: 6,
    damageCritical: 8,
    specialRules: [],
    criticalRules: [criticalRules.STUN],
    type: 'MELEE',
  },
  {
    name: 'Lightning claw',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.LETHAL5],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Lightning claws',
    profile: '',
    attackDice: 5,
    damage: 6,
    damageCritical: 8,
    specialRules: [specialRules.LETHAL5, specialRules.RELENTLESS],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Power fist',
    profile: '',
    attackDice: 5,
    weaponBallisticSkillAdjustment: 1,
    damage: 5,
    damageCritical: 7,
    specialRules: [specialRules.BRUTAL],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Power maul',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [],
    criticalRules: [criticalRules.STUN],
    type: 'MELEE',
  },
  {
    name: 'Power weapon',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 6,
    specialRules: [specialRules.LETHAL5],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Thunder hammer',
    profile: '',
    attackDice: 5,
    weaponBallisticSkillAdjustment: 1,
    damage: 5,
    damageCritical: 6,
    specialRules: [],
    criticalRules: [criticalRules.STUN],
    type: 'MELEE',
  },
  {
    name: 'Autogun',
    profile: '',
    attackDice: 4,
    damage: 2,
    damageCritical: 3,
    specialRules: [],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Shotgun',
    profile: '',
    attackDice: 4,
    weaponBallisticSkillAdjustment: -1,
    damage: 3,
    damageCritical: 3,
    specialRules: [specialRules.RNG6],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Boltgun',
    profile: 'Dragonfire',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.NO_COVER],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Boltgun',
    profile: 'Hellfire',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [criticalRules.RENDING],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Boltgun',
    profile: 'Kraken',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Boltgun',
    profile: 'Vengeance',
    attackDice: 4,
    damage: 4,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Shotgun',
    profile: 'Cryptclearer',
    attackDice: 4,
    damage: 4,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Shotgun',
    profile: 'Wyrmsbreath',
    attackDice: 5,
    weaponBallisticSkillAdjustment: -1,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.RNG3, specialRules.TORRENT],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Deathwatch Shotgun',
    profile: 'Xenopurge',
    attackDice: 4,
    weaponBallisticSkillAdjustment: -1,
    damage: 3,
    damageCritical: 5,
    specialRules: [specialRules.RNG6],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Stalker pattern boltgun',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.HEAVY, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Storm bolter',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RELENTLESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Frag Cannon',
    profile: 'Frag',
    attackDice: 4,
    damage: 4,
    damageCritical: 6,
    specialRules: [specialRules.BLAST2],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Frag Cannon',
    profile: 'Shell',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Auto bolt rifle',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.CEASELESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Heavy Bolter',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Heavy Bolter (CSM)',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Heavy Bolter (CSM)',
    profile: 'Malefic Rounds',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Heavy Bolter (CSM)',
    profile: 'Belt Feed',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE, specialRules.CEASELESS],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Infernus Heavy Bolter',
    profile: 'Heavy Bolter',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.FUSILLADE],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Infernus Heavy Bolter',
    profile: 'Heavy Flamer',
    attackDice: 6,
    fixedWeaponBallisticSkill: 2,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.HEAVY, specialRules.RNG6, specialRules.TORRENT],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Missile Launcher',
    profile: 'Frag',
    attackDice: 4,
    damage: 3,
    damageCritical: 5,
    specialRules: [specialRules.HEAVY, specialRules.BLAST2],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Missile Launcher',
    profile: 'Krak',
    attackDice: 4,
    damage: 5,
    damageCritical: 7,
    specialRules: [specialRules.HEAVY, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Boltgun (CSM)',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Boltgun (CSM)',
    profile: 'Belt Feed',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.CEASELESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Boltgun (CSM)',
    profile: 'Malefic Rounds',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Bolt pistol (CSM)',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RNG6],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Bolt pistol (CSM)',
    profile: 'Belt Feed',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RNG6, specialRules.CEASELESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Bolt pistol (CSM)',
    profile: 'Malefic Rounds',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RNG6],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Heavy stubber',
    profile: '',
    attackDice: 5,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.HEAVY, specialRules.CEASELESS, specialRules.FUSILLADE],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Mining laser',
    profile: '',
    attackDice: 5,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.HEAVY, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Seismic cannon',
    profile: 'Long-wave',
    attackDice: 6,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.HEAVY, specialRules.BLAST2],
    criticalRules: [criticalRules.STUN],
    type: 'RANGED',
  },
  {
    name: 'Seismic cannon',
    profile: 'Short-wave',
    attackDice: 4,
    weaponBallisticSkillAdjustment: -1,
    damage: 4,
    damageCritical: 4,
    specialRules: [specialRules.HEAVY, specialRules.RNG6],
    criticalRules: [criticalRules.STUN, criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Grenade launcher',
    profile: 'Frag',
    attackDice: 4,
    damage: 2,
    damageCritical: 4,
    specialRules: [specialRules.BLAST2],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Grenade launcher',
    profile: 'Krak',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Webber',
    profile: '',
    attackDice: 4,
    weaponBallisticSkillAdjustment: -1,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.RNG6, specialRules.LETHAL5],
    criticalRules: [criticalRules.STUN],
    type: 'RANGED',
  },
  {
    name: 'Flamer',
    profile: '',
    attackDice: 5,
    fixedWeaponBallisticSkill: 2,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.RNG6, specialRules.TORRENT],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Grav-gun',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.AP1, specialRules.GRAV],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Meltagun',
    profile: '',
    attackDice: 4,
    damage: 6,
    damageCritical: 3,
    specialRules: [specialRules.RNG6, specialRules.AP2],
    criticalRules: [criticalRules.MW4],
    type: 'RANGED',
  },
  {
    name: 'Plasma gun',
    profile: 'Standard',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Plasma gun',
    profile: 'Supercharge',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.AP2],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Combi-flamer',
    profile: '',
    attackDice: 5,
    fixedWeaponBallisticSkill: 2,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.COMBI, specialRules.RNG6, specialRules.TORRENT, specialRules.LIMITED],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Combi-grav',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.COMBI, specialRules.AP1, specialRules.GRAV, specialRules.LIMITED],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Combi-melta',
    profile: '',
    attackDice: 4,
    damage: 6,
    damageCritical: 3,
    specialRules: [specialRules.COMBI, specialRules.RNG6, specialRules.AP2, specialRules.LIMITED],
    criticalRules: [criticalRules.MW4],
    type: 'RANGED',
  },
  {
    name: 'Combi-plasma',
    profile: 'Standard',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.COMBI, specialRules.AP1, specialRules.LIMITED],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Combi-plasma',
    profile: 'Supercharge',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.COMBI, specialRules.AP2, specialRules.LIMITED],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Bolt pistol',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.RNG6],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Grav-pistol',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.RNG6, specialRules.AP1, specialRules.GRAV],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Hand flamer',
    profile: '',
    attackDice: 4,
    fixedWeaponBallisticSkill: 2,
    damage: 2,
    damageCritical: 2,
    specialRules: [specialRules.RNG6, specialRules.TORRENT],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Inferno pistol',
    profile: '',
    attackDice: 4,
    damage: 5,
    damageCritical: 3,
    specialRules: [specialRules.RNG3, specialRules.AP2],
    criticalRules: [criticalRules.MW3],
    type: 'RANGED',
  },
  {
    name: 'Plasma pistol',
    profile: 'Standard',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.RNG6, specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Plasma pistol',
    profile: 'Supercharge',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.RNG6, specialRules.AP2],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Plasma caliver',
    profile: 'Standard',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.AP1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Plasma caliver',
    profile: 'Supercharge',
    attackDice: 4,
    damage: 5,
    damageCritical: 6,
    specialRules: [specialRules.AP2, specialRules.HOT],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Galvanic rifle',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.HEAVY],
    criticalRules: [criticalRules.P1],
    type: 'RANGED',
  },
  {
    name: 'Arc rifle',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.AP1],
    criticalRules: [criticalRules.STUN],
    type: 'RANGED',
  },
  {
    name: 'Radium carbine',
    profile: '',
    attackDice: 4,
    damage: 2,
    damageCritical: 3,
    specialRules: [],
    criticalRules: [criticalRules.RENDING],
    type: 'RANGED',
  },
  {
    name: 'Arc pistol',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.RNG6, specialRules.AP1],
    criticalRules: [criticalRules.STUN],
    type: 'RANGED',
  },
  {
    name: 'Transuranic arquebus',
    profile: '',
    attackDice: 4,
    weaponBallisticSkillAdjustment: -1,
    damage: 5,
    damageCritical: 4,
    specialRules: [specialRules.AP1, specialRules.HEAVY, specialRules.UNWIELDY],
    criticalRules: [criticalRules.MW2],
    type: 'RANGED',
  },
  {
    name: 'Phosphor blast pistol',
    profile: '',
    attackDice: 4,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.RNG6, specialRules.BLAST1],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Radium pistol',
    profile: '',
    attackDice: 4,
    damage: 2,
    damageCritical: 3,
    specialRules: [specialRules.RNG6],
    criticalRules: [criticalRules.RENDING],
    type: 'RANGED',
  },
  {
    name: 'Flechette blaster',
    profile: '',
    attackDice: 5,
    damage: 2,
    damageCritical: 3,
    specialRules: [specialRules.RELENTLESS, specialRules.FUSILLADE, specialRules.RNG6],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Stubcarbine',
    profile: '',
    attackDice: 4,
    damage: 3,
    damageCritical: 4,
    specialRules: [specialRules.CEASELESS],
    criticalRules: [],
    type: 'RANGED',
  },
  {
    name: 'Chordclaw and transonic razor',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 5,
    specialRules: [specialRules.BALANCED],
    criticalRules: [],
    type: 'MELEE',
  },
  {
    name: 'Transonic blades',
    profile: '',
    attackDice: 5,
    damage: 4,
    damageCritical: 6,
    specialRules: [],
    criticalRules: [criticalRules.RENDING],
    type: 'MELEE',
  },
]
